version: "3"
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile.database
    volumes:
      - ./logs/postgresql:/var/log/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_DB: "database-name"
      POSTGRES_PASSWORD: "change-me"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
    tty: true
    container_name: postgresql-15
    networks:
      - default
